name: Cypress Tests
on:
  push:
  pull_request:
    branches:
    - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          GITHUB_TOKEN: ${{ secrets.PTA }}

      - name: Move HTML report to public
        if: always()
        run: |
          mkdir public
          cp -a cypress/reports/html/. public
      
      - name: Deploy report page to GitHub Page
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PTA }}
          publish_dir: ./public

      - name: Show run message
        if: always()
        run: |
          echo -n "View the test results [here](https://techbabette.github.io/QA-Final-assignment/)" >> $GITHUB_STEP_SUMMARY

      - name: Leave comment
        uses: actions/github-script@v5
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{secrets.PTA}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'View the test results [here](https://techbabette.github.io/QA-Final-assignment/)'
            })